name: Deploy WordPress to VPS

on:
  push:
    branches:
      - main  # Only trigger on push to main branch

jobs:
  install_and_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: fpm,mysql,curl,xml,zip,gd,mbstring  # Installing necessary PHP extensions

      - name: Install Composer dependencies
        run: |
          if [ -f "composer.json" ]; then
            composer install --no-interaction --prefer-dist --optimize-autoloader
          fi

      - name: Build the project (if applicable)
        run: |
          # Add any build steps here, e.g., building assets or compiling code.
          echo "Building the project..."

  deploy_files:
    needs: install_and_build  # Ensure this job runs after the install_and_build job completes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

      - name: Transfer files to VPS
        run: |
          rsync -avz --delete --rsync-path="sudo rsync" \
            -e "ssh -o StrictHostKeyChecking=no" \
            ./ ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:${{ secrets.VPS_PROJECT_PATH }}

  deploy_server:         #
    needs: deploy_files  # Ensure this job runs after the deploy_files job completes
    runs-on: ubuntu-latest
    steps:
      - name: Restart Nginx and PHP-FPM on VPS
        env:
          VPS_USER: ${{ secrets.VPS_USER }}
          VPS_HOST: ${{ secrets.VPS_HOST }}
        run: |
          ssh -tt -o StrictHostKeyChecking=no $VPS_USER@$VPS_HOST << EOF
            sudo systemctl restart nginx
            sudo systemctl restart php8.1-fpm
          EOF
