name: Provision Azure VPS for WordPress

on:
  push:
    branches:
      - main

jobs:
  provision:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Create Azure VM
        run: |
          az group create --name WordPressResourceGroup --location SouthIndia
          az vm create \
            --resource-group WordPressResourceGroup \
            --name WordPressVM \
            --image Ubuntu2204 \
            --admin-username azureuser \
            --generate-ssh-keys \
            --size Standard_B1s

      - name: Open necessary ports
        run: |
          az vm open-port --resource-group WordPressResourceGroup --name WordPressVM --port 80 --priority 1000
          az vm open-port --resource-group WordPressResourceGroup --name WordPressVM --port 443 --priority 1001

  configure:
    needs: provision
    runs-on: ubuntu-latest
    steps:
      - name: SSH into VM and Install LEMP Stack
        uses: appleboy/ssh-action@master
        with:
          host: ${{ steps.provision.outputs.vmIp }}
          username: azureuser
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo apt update
            sudo apt install -y nginx mysql-server php-fpm php-mysql

      - name: Configure Firewall
        run: |
          sudo ufw allow 'Nginx Full'
          sudo ufw allow OpenSSH
          sudo ufw enable

      - name: Configure MySQL
        run: |
          sudo mysql -e "CREATE DATABASE wordpress DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;"
          sudo mysql -e "CREATE USER 'wordpressuser'@'localhost' IDENTIFIED BY 'securepassword';"
          sudo mysql -e "GRANT ALL PRIVILEGES ON wordpress.* TO 'wordpressuser'@'localhost';"
          sudo mysql -e "FLUSH PRIVILEGES;"

      - name: Install WordPress
        run: |
          curl -O https://wordpress.org/latest.tar.gz
          tar -zxvf latest.tar.gz
          sudo cp -a wordpress/. /var/www/html/
          sudo chown -R www-data:www-data /var/www/html/
          sudo chmod -R 755 /var/www/html/

      - name: Configure Nginx
        run: |
          sudo tee /etc/nginx/sites-available/wordpress <<EOF
          server {
              listen 80;
              root /var/www/html;
              index index.php index.html index.htm;
              server_name your_domain_or_IP;
              location / {
                  try_files $uri $uri/ =404;
              }
              location ~ \.php$ {
                  include snippets/fastcgi-php.conf;
                  fastcgi_pass unix:/var/run/php/php-fpm.sock;
              }
              location ~ /\.ht {
                  deny all;
              }
          }
          EOF
          sudo ln -s /etc/nginx/sites-available/wordpress /etc/nginx/sites-enabled/
          sudo nginx -t
          sudo systemctl reload nginx
